### ISSUE TITLE
feat: Music feature but that replaces rickroll music 75% of the time

### ISSUE THREAD

**Issue by skepfusky** [thetayloredman/Lexi#519]
**Is your feature request related to a problem? Please describe.**
It's a mostly a feature request not related to a problem or issue.

**Describe the solution you'd like**
You normally play or queue your favorite music on the bot like you normally do but there's a 75% chance that it will just play to [Never Gonna Give You Up](https://youtu.be/iik25wqIuFo) despite playing a song that you choose nor queued it too but it will show the song name that you queued yet it plays rickroll music lol

**Describe alternatives you've considered**
Of courtse, you can turn this off and it is off by default since it can be annoying at times when queuing music.

**Additional context**
I dunno, probably a stupid yet a funny idea to prank your friends with this feature lmfao

- [ ] **This issue is part of the Lexi v3 rewrite:** https://github.com/thetayloredman/ProtoBot/pull/510

**Comment by thetayloredman** [comment]
A+ for [actually](https://github.com/thetayloredman/ProtoBot/issues/509) [filling](https://github.com/thetayloredman/ProtoBot/issues/75) [out](https://github.com/thetayloredman/ProtoBot/issues/502) [the](https://github.com/thetayloredman/ProtoBot/issues/495) [issue](https://github.com/thetayloredman/ProtoBot/issues/487) [template](https://github.com/thetayloredman/ProtoBot/issues/486). **Those are all separate links, by the way.**

I would need to put a lot of effort into music support, and I hope the bot doesn't get oof'd, but @ilikestohack has a nice implemtentation of it in r/skeppy if i could steal that

cc: @ilikestohack 
Linked in this issue: #509 #75 #502 #495 #487 #486
Refs: #510 
To-do-in: #510

**Comment by thetayloredman** [comment]
As is customary for our project...
@all-contributors please add @skepfusky for ideas

**Comment by thetayloredman** [comment]
@skepfusky Why was this closed?

**Comment by skepfusky** [comment]
I'm closing this again.
